### ISSUE TITLE
Do you have the mechanism to generate syzkaller description?

### ISSUE THREAD

**Issue by srikanth007m** [kartik-thakur/SyzkallerDescriptionGenerator#1]

**Comment by kartik-thakur** [comment]
I do have it but it is only generate description for IOCTL's.

Moreover, I never tested it thoroughly. You might face some issues for which I cannot provide help as I'm busy these days.

From: srikanth007m
Sent: Sunday, 15 September, 14:28
Subject: [kartik-thakur/SyzkallerDescriptionGenerator] Do you have the mechanism to generate syzkaller description? (#1)
To: kartik-thakur/SyzkallerDescriptionGenerator
Cc: Subscribed

**Comment by srikanth007m** [comment]
@kartik-thakur  thanks for the update.
